require "Foraging/forageSystem"
forageSkills = {

	unemployed = {
		name                    = "unemployed",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 20,
		darknessEffect          = 20,
		specialisations         = {
		["Firewood"]            = 5,
		["Stones"]              = 5,
		["Junk"]                = 10,
		["Trash"]               = 5,
		["Insects"]             = 5,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]		    = 5,
		["WildHerbs"]		    = 5,
		["JunkFood"]              = 10,
		["JunkWeapons"]           = 10,
		},
	},

	carpenter = {
		name                    = "carpenter",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 30,
		darknessEffect          = 20,
		specialisations         = {
		["Firewood"]              = 25,
		["Stones"]                = 10,
		["Junk"]                  = 5,
		["Trash"]                 = 5,
		["Insects"]               = 5,
		["Animals"]               = 5,
		["Berries"]               = 5,
		["Mushrooms"]             = 5,
		["Wild Plants"]           = 5,
		["WildHerbs"]             = 5,
		["JunkWeapons"]           = 5,
		},
	},
	
	cook = {
		name                    = "cook",
		type                    = "occupation",
		visionBonus = 2,
		weatherEffect = 25,
		darknessEffect = 25,
		specialisations         = {
		["Firewood"]            = 15,
		["Stones"]              = 15,
		["Junk"]                = 5,
		["Trash"]               = 5,
		["Insects"]             = 10,
		["Crops"] = 5,
		["Berries"]             = 10,
		["Mushrooms"]       = 5,
		["WildPlants"]          = 5,
		["WildHerbs"]         = 10
		},
	},

	healer = {
		name                    = "healer",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 25,
		darknessEffect          = 20,
		specialisations         = {
		["Medical"]             = 25,
		["MedicinalPlants"]   = 10,
		["Firewood"]            = 20,
		["Stones"]              = 20,
		["Junk"]                = 5,
		["Trash"]               = 5,
		["Insects"]             = 5,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]                    = 5,
		["WildHerbs"]                    = 5,
		},
	},

	farmer = {
		name                    = "farmer",
		type                    = "occupation",
		visionBonus             = 3,
		weatherEffect           = 30,
		darknessEffect          = 30,
		specialisations         = {
		["Firewood"]            = 20,
		["Stones"]              = 20,
		["Junk"]                = 10,
		["Trash"]               = 5,
		["Insects"]             = 10,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]            = 5,
		["WildHerbs"]                    = 5,
		["Fruits"]              = 15,
		["Vegetables"]          = 15,
		["Crops"]               = 15,
		},
	},	
	
	forager = {
		name                    = "forager",
		type                    = "occupation",
		visionBonus             = 5,
		weatherEffect           = 40,
		darknessEffect          = 40,
		specialisations         = {
		["ForestRarities"]      = 10,
		["JunkFood"]            = 15,
		["JunkWeapons"]         = 5,
		["Ammunition"]          = 1,
		["Medical"]             = 15,
		["MedicinalPlants"]     = 15,
		["FishBait"]            = 10,
		["Insects"]             = 10,
		["Animals"]             = 5,
		["Stones"]              = 25,
		["Firewood"]            = 25,
		["Junk"]                = 15,
		["Trash"]               = 15,
		["Berries"]             = 15,
		["Mushrooms"]           = 15,
		["WildPlants"]                    = 15,
		["WildHerbs"]                    = 15,
		["Fruits"]              = 15,
		["Vegetables"]          = 15,
		["Crops"]               = 10,
		},
	},

	mechanic = {
		name                    = "mechanic",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 25,
		darknessEffect          = 25,
		specialisations         = {
		["Firewood"]            = 15,
		["Stones"]              = 25,
		["Junk"]                = 10,
		["Trash"]               = 10,
		["Insects"]             = 5,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]                    = 5,
		["WildHerbs"]                    = 5,
		},
	},

	metalworker = {
		name                    = "metalworker",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 25,
		darknessEffect          = 25,
		specialisations         = {
		["Firewood"]            = 15,
		["Stones"]              = 25,
		["Junk"]                = 10,
		["Trash"]               = 10,
		["Insects"]             = 5,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]                    = 5,
		["WildHerbs"]                    = 5,
		},
	},

	musician = {
		name                    = "musician",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 25,
		darknessEffect          = 25,
		specialisations         = {
		["Firewood"]            = 20,
		["Stones"]              = 20,
		["Junk"]                = 10,
		["Trash"]               = 10,
		["Insects"]             = 5,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]                    = 5,
		["WildHerbs"]                    = 5,
		},
	},
	
	survivalist = {
		name                    = "survivalist",
		type                    = "occupation",
		visionBonus             = 4,
		weatherEffect           = 25,
		darknessEffect          = 25,
		specialisations         = {
		["Firewood"]            = 25,
		["Stones"]              = 25,
		["Junk"]                = 15,
		["Trash"]               = 15,
		["Insects"]             = 10,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]		    = 5,
		["WildHerbs"]		    = 15,
		},
	},

	tailor = {
		name                    = "tailor",
		type                    = "occupation",
		visionBonus             = 2,
		weatherEffect           = 25,
		darknessEffect          = 25,
		specialisations         = {
		["Firewood"]          = 20,
		["Stones"]              = 20,
		["Junk"]                  = 10,
		["Trash"]                 = 10,
		["Insects"]             = 5,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]                    = 5,
		["WildHerbs"]                    = 5,
		},
	},
	
	tinkerer = {
		name                    = "tinkerer",
		type                    = "occupation",
		visionBonus             = 3,
		weatherEffect           = 25,
		darknessEffect          = 55,
		specialisations         = {
		["Firewood"]            = 25,
		["Stones"]              = 25,
		["Junk"]                = 15,
		["Trash"]               = 15,
		["Insects"]             = 10,
		["Berries"]             = 5,
		["Mushrooms"]           = 5,
		["WildPlants"]		    = 5,
		["WildHerbs"]		    = 5,
		},
	},
}