local group = BodyLocations.getGroup("Human")
group:getOrCreateLocation("Cuirass")
group:getOrCreateLocation("Calf_Right")
group:getOrCreateLocation("Calf_Left")
group:getOrCreateLocation("ForeArm_Right")
group:getOrCreateLocation("ForeArm_Left")
group:getOrCreateLocation("Thigh_Right")
group:getOrCreateLocation("Thigh_Left")
group:getOrCreateLocation("ShoulderpadRight")
group:getOrCreateLocation("ShoulderpadLeft")
group:getOrCreateLocation("Codpiece")
group:getOrCreateLocation("Gorget")