DL = DL or {}
DL.Occupations = DL.Occupations or {}
local O = DL.Occupations

O.startingPoints = 22
O.defaultOccupation = "drifter"

O.pickLimits = {
    craft6 = 2,
    weapon = 2,
}

O.occupationOrder = {
    "drifter",
    "bruiser",
    "marksman",
    "skirmisher",
    "brawler",
    "ranger",
    "gravepicker",
    "sodbuster",
    "framer",
    "medic",
    "tinkerer",
    "homesteader",
    "greasehand",
    "smelter",
    "stitcher",
    "timberjack",
    "corpsman",
    "huntsman",
}

O.occupations = {
    drifter = {
        name = "Drifter",
        category = "Custom",
        description = "Build your own character from scratch.",
        preset = {},
    },
    bruiser = {
        name = "Bruiser",
        category = "Combat",
        description = "Bonebreaker - Long Blunt skill to Level 10\nFurtive - Nimble to Level 10",
        preset = { "bonebreaker", "furtive" },
    },
    marksman = {
        name = "Marksman",
        category = "Combat",
        description = "Dead-Eye - Aiming to Level 10\nSpeedloader - Reloading to Level 10",
        preset = { "dead_eye", "speedloader" },
    },
    skirmisher = {
        name = "Skirmisher",
        category = "Combat",
        description = "Cleaver - Long Blade skill to Level 10\nRoadburner - Sprinting to Level 10",
        preset = { "cleaver", "roadburner" },
    },
    brawler = {
        name = "Brawler",
        category = "Combat",
        description = "Wrestler - Grappling expert\nSlippery - Hard to pin down\nScrapper - Fights with whatever is at hand",
        preset = { "wrestler", "slippery", "scrapper" },
    },
    ranger = {
        name = "Ranger",
        category = "Survival",
        description = "Woodsman - Foraging, Trapping and Fishing to Level 6\nDeadly Quiet - Lightfooted to Level 10\nHerbalist - Can find medicinal plants and craft herbal medicines",
        preset = { "woodsman", "deadly_quiet", "Herbalist" },
    },
    gravepicker = {
        name = "Gravepicker",
        category = "Survival",
        description = "Woodsman - Foraging, Trapping and Fishing to Level 6\nCarrion Eye - Rare chance of finding corpses and shallow caches with various items\nIron Gut - Less chance for food illness",
        preset = { "woodsman", "carrion_eye", "IronGut" },
    },
    sodbuster = {
        name = "Sodbuster",
        category = "Survival",
        description = "Provisioner - Farming and Cooking to Level 10\nWoodsman - Foraging, Trapping and Fishing to Level 6",
        preset = { "provisioner", "woodsman" },
    },
    framer = {
        name = "Woodworker",
        category = "Crafting",
        description = "Timberwright - Carpentry to Level 10\nMetalhand - Metalworking to Level 6",
        preset = { "timberwright", "metalhand" },
    },
    medic = {
        name = "Medic",
        category = "Crafting",
        description = "Sawbones - First Aid to Level 10\nFurtive - Nimble to Level 10",
        preset = { "sawbones", "furtive" },
    },
    tinkerer = {
        name = "Tinkerer",
        category = "Crafting",
        description = "Sparky - Electrical to Level 10\nOilhand - Mechanics to Level 6",
        preset = { "sparky", "oilhand" },
    },
    homesteader = {
        name = "Homesteader",
        category = "Crafting",
        description = "Provisioner - Farming and Cooking to Level 10\nRoofraiser - Carpentry to Level 6",
        preset = { "provisioner", "roofraiser" },
    },
    greasehand = {
        name = "Greasehand",
        category = "Crafting",
        description = "Greasemonkey - Mechanics to Level 10\nMetalhand - Metalworking to Level 6",
        preset = { "greasemonkey", "metalhand" },
    },
    smelter = {
        name = "Smelter",
        category = "Crafting",
        description = "Blacksmith - Metalworking to Level 10\nOilhand - Mechanics to Level 6",
        preset = { "blacksmith", "oilhand" },
    },
    stitcher = {
        name = "Stitcher",
        category = "Crafting",
        description = "Clothier - Tailoring to Level 10\nWoodsman - Foraging, Trapping and Fishing to Level 6\nForage: Bones & Hide - Can forage bones and hide",
        preset = { "clothier", "woodsman" },
        choices = { "forage_bones" },
    },
    timberjack = {
        name = "Timberjack",
        category = "Hybrid",
        description = "Limbsplitter - Axe skill to Level 10\nTimberwright - Carpentry to Level 10",
        preset = { "limbsplitter", "timberwright" },
    },
    corpsman = {
        name = "Corpsman",
        category = "Hybrid",
        description = "Longreach - Spear skill to Level 10\nFirst Aid - First Aid to Level 6",
        preset = { "longreach", "first_aid" },
    },
    huntsman = {
        name = "Huntsman",
        category = "Hybrid",
        description = "Woodsman - Foraging, Trapping and Fishing to Level 6\nSpotter - Aiming to Level 8\nTracker - Increased chances of finding animal tracks to find and hunt animals",
        preset = { "woodsman", "spotter", "tracker" },
    },
}

O.traitOrder = {
    "Athletic",
    "Fit",
    "Out of Shape",
    "Unfit",
    "Strong",
    "Stout",
    "Feeble",
    "Weak",
    "SpeedDemon",
    "SundayDriver",
    "LowThirst",
    "HighThirst",
    "LightEater",
    "HeartyAppitite",
    "Organized",
    "Disorganized",
    "ThickSkinned",
    "Thinskinned",
    "FastHealer",
    "SlowHealer",
    "Dextrous",
    "AllThumbs",
    "NightVision",
    "EagleEyed",
    "Graceful",
    "Clumsy",
    "Inconspicuous",
    "Conspicuous",
    "KeenHearing",
    "HardOfHearing",
    "Herbalist",
    "IronGut",
    "FastReader",
    "Resilient",
    "Outdoorsman",
    "Asthmatic",
    "Hemophobic",
    "ShortSighted",
    "hewer",
    "cudgeller",
    "thumper",
    "slasher",
    "cutter",
    "sticker",
    "limbsplitter",
    "bonebreaker",
    "skullcracker",
    "cleaver",
    "redhand",
    "longreach",
    "dead_eye",
    "roofraiser",
    "cottager",
    "first_aid",
    "tinkerer_t",
    "metalhand",
    "oilhand",
    "patcher",
    "timberwright",
    "provisioner",
    "sawbones",
    "sparky",
    "blacksmith",
    "greasemonkey",
    "clothier",
    "longstrider",
    "softstep",
    "spry",
    "prowler",
    "roadburner",
    "deadly_quiet",
    "furtive",
    "ghost",
    "musician",
    "maestro",
    "woodsman",
    "provider",
    "carrion_eye",
    "tracker",
    "harvest_child",
    "maniacal",
    "polyglot",
    "oilstone",
    "speedloader",
    "hoarder",
    "addict",
    "productive",
    "slow_worker",
    "heavyweight",
    "featherweight",
    "lunger",
    "wildcard",
    "even_keel",
    "lucky_dice",
    "unlucky_dice",
    "evasive",
    "sturdy",
    "quickdraw",
    "spearwall",
    "strong_arm",
    "wrestler",
    "scrapper",
    "slippery",
    "tireless",
    "iron_will",
    "asthmatic_dice",
    "faint_hearted",
    "snapshooter",
    "gunslinger",
    "rifleman",
    "spotter",
    "longshot",
    "forage_chemicals",
    "forage_metals",
    "forage_bones",
    "forage_alcohol",
    "forage_ores",
    "forage_urban",
    "addiction_opiate",
    "addiction_stimulant",
    "addiction_depressant",
    "addiction_hallucinogen",
    "addiction_inhalant",
    "glass_jaw",
    "bullet_magnet",
    "heavy_footed",
    "lumbering",
    "daydreamer",
    "oblivious",
    "timid",
    "meek",
    "addiction_alcohol",
}

O.traits = {
    Athletic = {
        planner = "athletic",
        name = "Athletic",
        description = "+4 Starting Fitness",
        cost = 10,
        section = "Body & Stats",
        xp = { Fitness = 4 },
    },
    Fit = {
        planner = "fit",
        name = "Fit",
        description = "+2 Starting Fitness",
        cost = 8,
        section = "Body & Stats",
        xp = { Fitness = 2 },
    },
    ["Out of Shape"] = {
        planner = "out_of_shape",
        name = "Out of Shape",
        description = "-2 Starting Fitness",
        cost = -2,
        section = "Body & Stats",
        xp = { Fitness = -2 },
    },
    Unfit = {
        planner = "unfit",
        name = "Unfit",
        description = "-4 Starting Fitness",
        cost = -4,
        section = "Body & Stats",
        xp = { Fitness = -4 },
    },
    Strong = {
        planner = "strong",
        name = "Strong",
        description = "+4 Starting Strength",
        cost = 10,
        section = "Body & Stats",
        xp = { Strength = 4 },
    },
    Stout = {
        planner = "stout",
        name = "Stout",
        description = "+2 Starting Strength",
        cost = 8,
        section = "Body & Stats",
        xp = { Strength = 2 },
    },
    Feeble = {
        planner = "weak",
        name = "Weak",
        description = "-2 Starting Strength",
        cost = -2,
        section = "Body & Stats",
        xp = { Strength = -2 },
    },
    Weak = {
        planner = "feeble",
        name = "Feeble",
        description = "-4 Starting Strength",
        cost = -4,
        section = "Body & Stats",
        xp = { Strength = -4 },
    },
    SpeedDemon = {
        planner = "speed_demon",
        name = "Speed Demon",
        description = "Faster Driver + Offroader",
        cost = 2,
        section = "Lifestyle & Utility",
    },
    SundayDriver = {
        planner = "sunday_driver",
        name = "Sunday Driver",
        description = "Slower Driver",
        cost = -2,
        section = "Lifestyle & Utility",
    },
    LowThirst = {
        planner = "low_thirst",
        name = "Low Thirst",
        description = "Drink Less",
        cost = 4,
        section = "Lifestyle & Utility",
    },
    HighThirst = {
        planner = "high_thirst",
        name = "High Thirst",
        description = "Drink More",
        cost = -2,
        section = "Lifestyle & Utility",
    },
    LightEater = {
        planner = "light_eater",
        name = "Light Eater",
        description = "Eat Less",
        cost = 4,
        section = "Lifestyle & Utility",
    },
    HeartyAppitite = {
        planner = "hearty_appetite",
        name = "Hearty Appetite",
        description = "Eat More",
        cost = -2,
        section = "Lifestyle & Utility",
    },
    Organized = {
        planner = "organized",
        name = "Organized",
        description = "Increased Inventory",
        cost = 4,
        section = "Lifestyle & Utility",
    },
    Disorganized = {
        planner = "disorganized",
        name = "Disorganized",
        description = "Decreased Inventory",
        cost = -2,
        section = "Lifestyle & Utility",
    },
    ThickSkinned = {
        planner = "thick_skinned",
        name = "Thick-Skinned",
        description = "Less likely to be injured\n\nDice: Advantage to DWD Rolls",
        cost = 10,
        section = "Body & Stats",
    },
    Thinskinned = {
        planner = "thin_skinned",
        name = "Thin-Skinned",
        description = "More likely to be injured\n\nDice: Disadvantage to DWD Rolls",
        cost = -4,
        section = "Body & Stats",
    },
    FastHealer = {
        planner = "fast_healer",
        name = "Fast Healer",
        description = "Recovers faster from injuries",
        cost = 4,
        section = "Body & Stats",
    },
    SlowHealer = {
        planner = "slow_healer",
        name = "Slow Healer",
        description = "Recovers slower from injuries",
        cost = -2,
        section = "Body & Stats",
    },
    Dextrous = {
        planner = "dextrous",
        name = "Dextrous",
        description = "Faster Inventory Transfer\n\nDice: +1 to Initiative",
        cost = 4,
        section = "Senses & Reflexes",
    },
    AllThumbs = {
        planner = "all_thumbs",
        name = "All Thumbs",
        description = "Slower Inventory Transfer\n\nDice: -1 to Initiative",
        cost = -2,
        section = "Senses & Reflexes",
    },
    NightVision = {
        planner = "cats_eyes",
        name = "Cat's Eyes",
        description = "Better vision at night\n\nDice: +1 to Notice",
        cost = 2,
        section = "Senses & Reflexes",
    },
    EagleEyed = {
        planner = "eagle_eyes",
        name = "Eagle Eyes",
        description = "Higher visibility arc\n\nDice: +1 to Notice",
        cost = 2,
        section = "Senses & Reflexes",
    },
    Graceful = {
        planner = "graceful",
        name = "Graceful",
        description = "Make less noise\n\nDice: +1 to Hide",
        cost = 4,
        section = "Stealth",
    },
    Clumsy = {
        planner = "clumsy",
        name = "Clumsy",
        description = "Make more noise\n\nDice: -1 to Hide",
        cost = -2,
        section = "Stealth",
    },
    Inconspicuous = {
        planner = "inconspicuous",
        name = "Inconspicuous",
        description = "Less likely to be spotted\n\nDice: +1 to Hide",
        cost = 4,
        section = "Stealth",
    },
    Conspicuous = {
        planner = "conspicuous",
        name = "Conspicuous",
        description = "More likely to be spotted\n\nDice: -1 to Hide",
        cost = -2,
        section = "Stealth",
    },
    KeenHearing = {
        planner = "keen_hearing",
        name = "Keen Hearing",
        description = "Larger vision arc behind character\n\nDice: +1 to Notice",
        cost = 4,
        section = "Senses & Reflexes",
    },
    HardOfHearing = {
        planner = "hard_of_hearing",
        name = "Hard of Hearing",
        description = "No vision behind character\n\nDice: -2 to Notice",
        cost = -2,
        section = "Senses & Reflexes",
    },
    Herbalist = {
        planner = "herbalist",
        name = "Herbalist",
        description = "Can find medicinal plants and craft herbal medicines",
        cost = 2,
        section = "Survival",
        recipes = { "Herbalist" },
    },
    IronGut = {
        planner = "iron_gut",
        name = "Iron Gut",
        description = "Less chance for food illness",
        cost = 2,
        section = "Survival",
    },
    FastReader = {
        planner = "fast_reader",
        name = "Fast Reader",
        description = "Read books faster",
        cost = 2,
        section = "Lifestyle & Utility",
    },
    Resilient = {
        planner = "resilient",
        name = "Resilient",
        description = "Less prone to disease",
        cost = 2,
        section = "Survival",
    },
    Outdoorsman = {
        planner = "outdoorsy",
        name = "Outdoorsy",
        description = "Less chance of cold and tree wounds",
        cost = 4,
        section = "Survival",
    },
    Asthmatic = {
        planner = "short_of_breath",
        name = "Short of Breath",
        description = "Faster endurance loss\n\nDice: -1 to Physical Endurance",
        cost = -2,
        section = "Body & Stats",
    },
    Hemophobic = {
        planner = "fear_of_blood",
        name = "Fear of Blood",
        description = "Panic from blood, no first aid on others\n\nDice: -1 to Mental Endurance",
        cost = -2,
        section = "Mind",
    },
    ShortSighted = {
        planner = "poor_eyesight",
        name = "Poor Eyesight",
        description = "Worse eyesight\n\nDice: -2 to Notice",
        cost = -2,
        section = "Senses & Reflexes",
    },
    hewer = {
        planner = "hewer",
        name = "Hewer",
        description = "Axe skill to Level 8\n\nDice: +2 to Attack when using Axes",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { Axe = 8 },
    },
    cudgeller = {
        planner = "cudgeller",
        name = "Cudgeller",
        description = "Long Blunt skill to Level 8\n\nDice: +2 to Attack when using Long Blunts",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { Blunt = 8 },
    },
    thumper = {
        planner = "thumper",
        name = "Thumper",
        description = "Short Blunt skill to Level 8\n\nDice: +2 to Attack when using Short Blunts",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { SmallBlunt = 8 },
    },
    slasher = {
        planner = "slasher",
        name = "Slasher",
        description = "Long Blade skill to Level 8\n\nDice: +2 to Attack when using Long Blades",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { LongBlade = 8 },
    },
    cutter = {
        planner = "cutter",
        name = "Cutter",
        description = "Short Blade skill to Level 8\n\nDice: +2 to Attack when using Short Blades",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { SmallBlade = 8 },
    },
    sticker = {
        planner = "sticker",
        name = "Sticker",
        description = "Spear skill to Level 8\n\nDice: +2 to Attack when using Spears",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { Spear = 8 },
    },
    limbsplitter = {
        planner = "limbsplitter",
        name = "Limbsplitter",
        description = "Axe skill to Level 10\n\nDice: +4 to Attack when using Axes",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { Axe = 10 },
    },
    bonebreaker = {
        planner = "bonebreaker",
        name = "Bonebreaker",
        description = "Long Blunt skill to Level 10\n\nDice: +4 to Attack when using Long Blunts",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { Blunt = 10 },
    },
    skullcracker = {
        planner = "skullcracker",
        name = "Skullcracker",
        description = "Short Blunt skill to Level 10\n\nDice: +4 to Attack when using Short Blunts",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { SmallBlunt = 10 },
    },
    cleaver = {
        planner = "cleaver",
        name = "Cleaver",
        description = "Long Blade skill to Level 10\n\nDice: +4 to Attack when using Long Blades",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { LongBlade = 10 },
    },
    redhand = {
        planner = "redhand",
        name = "Redhand",
        description = "Short Blade skill to Level 10\n\nDice: +4 to Attack when using Short Blades",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { SmallBlade = 10 },
    },
    longreach = {
        planner = "longreach",
        name = "Longreach",
        description = "Spear skill to Level 10\n\nDice: +4 to Attack when using Spears",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { Spear = 10 },
    },
    dead_eye = {
        planner = "dead_eye",
        name = "Dead-Eye",
        description = "Aiming to Level 10\n\nDice: +2 to Attack with Guns; +2 to Attack with Medium Range Guns",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { Aiming = 10 },
    },
    roofraiser = {
        planner = "roofraiser",
        name = "Roofraiser",
        description = "Carpentry to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { Woodwork = 6 },
    },
    cottager = {
        planner = "cottager",
        name = "Cottager",
        description = "Farming and Cooking to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { Farming = 6, Cooking = 6 },
    },
    first_aid = {
        planner = "first_aid",
        name = "First Aid",
        description = "First Aid to Level 6\n\nDice: +1 to First Aid Rolls",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { Doctor = 6 },
    },
    tinkerer_t = {
        planner = "tinkerer_t",
        name = "Tinkerer",
        description = "Electrical to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { Electricity = 6 },
    },
    metalhand = {
        planner = "metalhand",
        name = "Metalhand",
        description = "Metalworking to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { MetalWelding = 6 },
    },
    oilhand = {
        planner = "oilhand",
        name = "Oilhand",
        description = "Mechanics to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { Mechanics = 6 },
    },
    patcher = {
        planner = "patcher",
        name = "Patcher",
        description = "Tailoring to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { Tailoring = 6 },
    },
    timberwright = {
        planner = "timberwright",
        name = "Timberwright",
        description = "Carpentry to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { Woodwork = 10 },
    },
    provisioner = {
        planner = "provisioner",
        name = "Provisioner",
        description = "Farming and Cooking to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { Farming = 10, Cooking = 10 },
    },
    sawbones = {
        planner = "sawbones",
        name = "Sawbones",
        description = "First Aid to Level 10\n\nDice: +2 to First Aid Rolls",
        cost = 8,
        section = "Skill Mastery",
        caps = { Doctor = 10 },
    },
    sparky = {
        planner = "sparky",
        name = "Sparky",
        description = "Electrical to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { Electricity = 10 },
    },
    blacksmith = {
        planner = "blacksmith",
        name = "Blacksmith",
        description = "Metalworking to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { MetalWelding = 10 },
    },
    greasemonkey = {
        planner = "greasemonkey",
        name = "Greasemonkey",
        description = "Mechanics to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { Mechanics = 10 },
    },
    clothier = {
        planner = "clothier",
        name = "Clothier",
        description = "Tailoring to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { Tailoring = 10 },
    },
    longstrider = {
        planner = "longstrider",
        name = "Longstrider",
        description = "Sprinting to Level 8\n\nDice: +1 to Defend Ranged",
        cost = 4,
        section = "Agility",
        caps = { Sprinting = 8 },
    },
    softstep = {
        planner = "softstep",
        name = "Softstep",
        description = "Lightfooted to Level 8\n\nDice: +1 to Hide",
        cost = 4,
        section = "Agility",
        caps = { Lightfoot = 8 },
    },
    spry = {
        planner = "spry",
        name = "Spry",
        description = "Nimble to Level 8\n\nDice: +1 to Defend Close",
        cost = 4,
        section = "Agility",
        caps = { Nimble = 8 },
    },
    prowler = {
        planner = "prowler",
        name = "Prowler",
        description = "Sneaking to Level 8\n\nDice: +1 to Hide",
        cost = 4,
        section = "Agility",
        caps = { Sneak = 8 },
    },
    roadburner = {
        planner = "roadburner",
        name = "Roadburner",
        description = "Sprinting to Level 10\n\nDice: +2 to Defend Ranged",
        cost = 6,
        section = "Agility",
        caps = { Sprinting = 10 },
    },
    deadly_quiet = {
        planner = "deadly_quiet",
        name = "Deadly Quiet",
        description = "Lightfooted to Level 10\n\nDice: +2 to Hide",
        cost = 6,
        section = "Agility",
        caps = { Lightfoot = 10 },
    },
    furtive = {
        planner = "furtive",
        name = "Furtive",
        description = "Nimble to Level 10\n\nDice: +2 to Defend Close",
        cost = 6,
        section = "Agility",
        caps = { Nimble = 10 },
    },
    ghost = {
        planner = "ghost",
        name = "Ghost",
        description = "Sneaking to Level 10\n\nDice: +2 to Hide",
        cost = 6,
        section = "Agility",
        caps = { Sneak = 10 },
    },
    musician = {
        planner = "musician",
        name = "Musician",
        description = "Can play most songs, still need to find sheet music first",
        cost = 2,
        section = "Lifestyle & Utility",
        add = { "HobbyMusic" },
    },
    maestro = {
        planner = "maestro",
        name = "Maestro",
        description = "Can play all songs, still need to find sheet music first",
        cost = 4,
        section = "Lifestyle & Utility",
        add = { "profmusician" },
    },
    woodsman = {
        planner = "woodsman",
        name = "Woodsman",
        description = "Foraging, Trapping and Fishing to Level 6",
        cost = 4,
        section = "Skills (Pick Up To 2)",
        group = "craft6",
        caps = { PlantScavenging = 6, Trapping = 6, Fishing = 6 },
    },
    provider = {
        planner = "provider",
        name = "Provider",
        description = "Foraging, Trapping and Fishing to Level 10",
        cost = 8,
        section = "Skill Mastery",
        caps = { PlantScavenging = 10, Trapping = 10, Fishing = 10 },
    },
    carrion_eye = {
        planner = "carrion_eye",
        name = "Carrion Eye",
        description = "Rare chance of finding corpses and shallow caches with various items",
        cost = 4,
        section = "Survival",
    },
    tracker = {
        planner = "tracker",
        name = "Tracker",
        description = "Increased chances of finding animal tracks to find and hunt animals",
        cost = 4,
        section = "Survival",
    },
    harvest_child = {
        planner = "harvest_child",
        name = "Harvest Child",
        description = "More prone to disease, less likely to be spotted (Harvest Lore)",
        cost = 4,
        section = "Survival",
        add = { "ProneToIllness", "Inconspicuous" },
    },
    maniacal = {
        planner = "maniacal",
        name = "Maniacal",
        description = "Lose unhappiness depending on how bloody you are",
        cost = 2,
        section = "Mind",
    },
    polyglot = {
        planner = "polyglot",
        name = "Polyglot",
        description = "Start with one additional known language",
        cost = 2,
        section = "Lifestyle & Utility",
    },
    oilstone = {
        planner = "oilstone",
        name = "Oilstone",
        description = "Maintenance to Level 10",
        cost = 4,
        section = "Firearms & Upkeep",
        caps = { Maintenance = 10 },
    },
    speedloader = {
        planner = "speedloader",
        name = "Speedloader",
        description = "Reloading to Level 10",
        cost = 4,
        section = "Firearms & Upkeep",
        caps = { Reloading = 10 },
    },
    hoarder = {
        planner = "hoarder",
        name = "Hoarder",
        description = "20% extra carry capacity, but SEVERE stress below 50% capacity",
        cost = 2,
        section = "Lifestyle & Utility",
    },
    addict = {
        planner = "addict",
        name = "Addict",
        description = "Start with one addiction of choice",
        cost = -2,
        section = "Mind",
    },
    productive = {
        planner = "productive",
        name = "Productive",
        description = "All Timed Actions are faster",
        cost = 4,
        section = "Lifestyle & Utility",
    },
    slow_worker = {
        planner = "slow_worker",
        name = "Slow Worker",
        description = "All Timed Actions are slower",
        cost = -2,
        section = "Lifestyle & Utility",
    },
    heavyweight = {
        planner = "heavyweight",
        name = "Heavyweight",
        description = "Slow but hits hard\n\nDice: -1 Movement Point per turn; +1 to Attack with Melee",
        cost = 2,
        section = "Combat Dice",
    },
    featherweight = {
        planner = "featherweight",
        name = "Featherweight",
        description = "Fast but hits soft\n\nDice: +1 Movement Point per turn; -1 to Attack with Melee",
        cost = 2,
        section = "Combat Dice",
    },
    lunger = {
        planner = "lunger",
        name = "Lunger",
        description = "Devastating charges\n\nDice: +2 to Attack with Melee after moving 3+ tiles in a straight line",
        cost = 2,
        section = "Combat Dice",
    },
    wildcard = {
        planner = "wildcard",
        name = "Wildcard",
        description = "Feast or famine\n\nDice: Crit Success on 19-20; Crit Fail on 1-2",
        cost = 2,
        section = "Combat Dice",
    },
    even_keel = {
        planner = "even_keel",
        name = "Even Keel",
        description = "Steady as she goes\n\nDice: No Critical Successes; No Critical Failures",
        cost = 2,
        section = "Combat Dice",
    },
    lucky_dice = {
        planner = "lucky",
        name = "Lucky",
        description = "Somehow it never sticks\n\nDice: Status effects end one turn shorter (1 turn minimum)",
        cost = 4,
        section = "Combat Dice",
    },
    unlucky_dice = {
        planner = "unlucky",
        name = "Unlucky",
        description = "It always sticks\n\nDice: Status effects last one turn longer",
        cost = -2,
        section = "Combat Dice",
    },
    evasive = {
        planner = "evasive",
        name = "Evasive",
        description = "Harder to shoot, easier to corner\n\nDice: +1 to Defend Ranged; -1 to Defend Close",
        cost = 2,
        section = "Combat Dice",
    },
    sturdy = {
        planner = "sturdy",
        name = "Sturdy",
        description = "Harder to corner, easier to shoot\n\nDice: +1 to Defend Close; -1 to Defend Ranged",
        cost = 2,
        section = "Combat Dice",
    },
    quickdraw = {
        planner = "quickdraw",
        name = "Quickdraw",
        description = "Fastest gun in the wastes\n\nDice: +3 to Initiative if you start the fight holding a pistol, removed if you swap",
        cost = 2,
        section = "Combat Dice",
    },
    spearwall = {
        planner = "spearwall",
        name = "Spearwall",
        description = "Hold the line\n\nDice: -2 to Attack; Attack of Opportunity when someone leaves your melee range, needs a two handed melee weapon",
        cost = 4,
        section = "Combat Dice",
    },
    strong_arm = {
        planner = "strong_arm",
        name = "Strong Arm",
        description = "Born to throw\n\nDice: +1 thrown damage and +3 throw range; Can throw short blunt and short blade weapons; -1 to non-thrown attacks",
        cost = 2,
        section = "Combat Dice",
    },
    wrestler = {
        planner = "wrestler",
        name = "Wrestler",
        description = "Grappling expert\n\nDice: +2 to Grapple and Escape Grapple",
        cost = 4,
        section = "Combat Dice",
    },
    scrapper = {
        planner = "scrapper",
        name = "Scrapper",
        description = "Fights with whatever is at hand\n\nDice: +1 to Attack when using Unarmed and Improvised",
        cost = 2,
        section = "Combat Dice",
    },
    slippery = {
        planner = "slippery",
        name = "Slippery",
        description = "Hard to pin down\n\nDice: +2 to Escape",
        cost = 2,
        section = "Combat Dice",
    },
    tireless = {
        planner = "tireless",
        name = "Tireless",
        description = "Keeps going\n\nDice: +2 to Physical Endurance",
        cost = 4,
        section = "Combat Dice",
    },
    iron_will = {
        planner = "iron_will",
        name = "Iron Will",
        description = "Unshakeable\n\nDice: +2 to Mental Endurance",
        cost = 4,
        section = "Combat Dice",
    },
    asthmatic_dice = {
        planner = "asthmatic",
        name = "Asthmatic",
        description = "Winded easily\n\nDice: -3 to Physical Endurance",
        cost = -2,
        section = "Combat Dice",
    },
    faint_hearted = {
        planner = "faint_hearted",
        name = "Faint-Hearted",
        description = "Cracks under pressure\n\nDice: -3 to Mental Endurance",
        cost = -2,
        section = "Combat Dice",
    },
    snapshooter = {
        planner = "snapshooter",
        name = "Snapshooter",
        description = "Aiming to Level 8\n\nDice: +1 to Attack with Guns; +1 to Attack with Close Range Guns",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { Aiming = 8 },
    },
    gunslinger = {
        planner = "gunslinger",
        name = "Gunslinger",
        description = "Aiming to Level 10\n\nDice: +2 to Attack with Guns; +2 to Attack with Close Range Guns",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { Aiming = 10 },
    },
    rifleman = {
        planner = "rifleman",
        name = "Rifleman",
        description = "Aiming to Level 8\n\nDice: +1 to Attack with Guns; +1 to Attack with Medium Range Guns",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { Aiming = 8 },
    },
    spotter = {
        planner = "spotter",
        name = "Spotter",
        description = "Aiming to Level 8\n\nDice: +1 to Attack with Guns; +1 to Attack with Long Range Guns",
        cost = 6,
        section = "Weapons",
        group = "weapon",
        caps = { Aiming = 8 },
    },
    longshot = {
        planner = "longshot",
        name = "Longshot",
        description = "Aiming to Level 10\n\nDice: +2 to Attack with Guns; +2 to Attack with Long Range Guns",
        cost = 8,
        section = "Weapons",
        group = "weapon",
        caps = { Aiming = 10 },
    },
    forage_chemicals = {
        planner = "forage_chemicals",
        name = "Forage: Chemicals",
        description = "Can forage chemicals",
        cost = 0,
        section = "Survival",
        hidden = true,
    },
    forage_metals = {
        planner = "forage_metals",
        name = "Forage: Metals & Supplies",
        description = "Can forage metals and supplies",
        cost = 0,
        section = "Survival",
        hidden = true,
    },
    forage_bones = {
        planner = "forage_bones",
        name = "Forage: Bones & Hide",
        description = "Can forage bones and hide",
        cost = 0,
        section = "Survival",
        hidden = true,
    },
    forage_alcohol = {
        planner = "forage_alcohol",
        name = "Forage: Alcohol & Distilling",
        description = "Can forage alcohol or distilling supplies",
        cost = 0,
        section = "Survival",
        hidden = true,
    },
    forage_ores = {
        planner = "forage_ores",
        name = "Forage: Ores, Metals & Supplies",
        description = "Can forage ores, metals and supplies",
        cost = 0,
        section = "Survival",
        hidden = true,
    },
    forage_urban = {
        planner = "forage_urban",
        name = "Forage: Urban Tech",
        description = "Can forage urban tech such as wire, screws, nails, batteries, tools and so on",
        cost = 0,
        section = "Survival",
        hidden = true,
    },
    addiction_opiate = {
        planner = "addiction_opiate",
        name = "Opiate Addiction",
        description = "",
        cost = 0,
        section = "Mind",
        hidden = true,
    },
    addiction_stimulant = {
        planner = "addiction_stimulant",
        name = "Stimulant Addiction",
        description = "",
        cost = 0,
        section = "Mind",
        hidden = true,
    },
    addiction_depressant = {
        planner = "addiction_depressant",
        name = "Depressant Addiction",
        description = "",
        cost = 0,
        section = "Mind",
        hidden = true,
    },
    addiction_hallucinogen = {
        planner = "addiction_hallucinogen",
        name = "Hallucinogen Addiction",
        description = "",
        cost = 0,
        section = "Mind",
        hidden = true,
    },
    addiction_inhalant = {
        planner = "addiction_inhalant",
        name = "Inhalant Addiction",
        description = "",
        cost = 0,
        section = "Mind",
        hidden = true,
    },
    glass_jaw = {
        planner = "glass_jaw",
        name = "Glass Jaw",
        description = "Can't take a punch\n\nDice: -4 to Defend Close",
        cost = -2,
        section = "Combat Dice",
    },
    bullet_magnet = {
        planner = "bullet_magnet",
        name = "Bullet Magnet",
        description = "Always in the line of fire\n\nDice: -4 to Defend Ranged",
        cost = -2,
        section = "Combat Dice",
    },
    heavy_footed = {
        planner = "heavy_footed",
        name = "Heavy-Footed",
        description = "Every step announces you\n\nDice: -1 to Hide",
        cost = -1,
        section = "Stealth",
    },
    lumbering = {
        planner = "lumbering",
        name = "Lumbering",
        description = "Built like a barn door, moves like one\n\nDice: -2 to Hide",
        cost = -2,
        section = "Stealth",
    },
    daydreamer = {
        planner = "daydreamer",
        name = "Daydreamer",
        description = "Head in the clouds\n\nDice: -1 to Notice",
        cost = -1,
        section = "Senses & Reflexes",
    },
    oblivious = {
        planner = "oblivious",
        name = "Oblivious",
        description = "Misses what's right in front of them\n\nDice: -2 to Notice",
        cost = -2,
        section = "Senses & Reflexes",
    },
    timid = {
        planner = "timid",
        name = "Timid",
        description = "Reluctant to do harm\n\nDice: -2 to Attack with Melee; -2 to Attack with Ranged",
        cost = -2,
        section = "Combat Dice",
    },
    meek = {
        planner = "meek",
        name = "Meek",
        description = "Violence doesn't come naturally\n\nDice: -4 to Attack with Melee; -4 to Attack with Ranged",
        cost = -4,
        section = "Combat Dice",
    },
    addiction_alcohol = {
        planner = "addiction_alcohol",
        name = "Alcohol Addiction",
        description = "",
        cost = 0,
        section = "Mind",
        hidden = true,
    },
}

O.exclusives = {
    { "Athletic", "Fit" },
    { "Athletic", "Out of Shape" },
    { "Athletic", "Unfit" },
    { "Fit", "Out of Shape" },
    { "Fit", "Unfit" },
    { "Out of Shape", "Unfit" },
    { "Strong", "Stout" },
    { "Strong", "Feeble" },
    { "Strong", "Weak" },
    { "Stout", "Feeble" },
    { "Stout", "Weak" },
    { "Feeble", "Weak" },
    { "SpeedDemon", "SundayDriver" },
    { "LowThirst", "HighThirst" },
    { "LightEater", "HeartyAppitite" },
    { "Organized", "Disorganized" },
    { "ThickSkinned", "Thinskinned" },
    { "FastHealer", "SlowHealer" },
    { "Dextrous", "AllThumbs" },
    { "NightVision", "EagleEyed" },
    { "Graceful", "Clumsy" },
    { "Inconspicuous", "Conspicuous" },
    { "KeenHearing", "HardOfHearing" },
    { "timberwright", "provisioner" },
    { "timberwright", "sawbones" },
    { "timberwright", "sparky" },
    { "timberwright", "blacksmith" },
    { "timberwright", "greasemonkey" },
    { "timberwright", "clothier" },
    { "provisioner", "sawbones" },
    { "provisioner", "sparky" },
    { "provisioner", "blacksmith" },
    { "provisioner", "greasemonkey" },
    { "provisioner", "clothier" },
    { "sawbones", "sparky" },
    { "sawbones", "blacksmith" },
    { "sawbones", "greasemonkey" },
    { "sawbones", "clothier" },
    { "sparky", "blacksmith" },
    { "sparky", "greasemonkey" },
    { "sparky", "clothier" },
    { "blacksmith", "greasemonkey" },
    { "blacksmith", "clothier" },
    { "greasemonkey", "clothier" },
    { "longstrider", "roadburner" },
    { "softstep", "deadly_quiet" },
    { "spry", "furtive" },
    { "prowler", "ghost" },
    { "musician", "maestro" },
    { "woodsman", "provider" },
    { "harvest_child", "Inconspicuous" },
    { "harvest_child", "Resilient" },
    { "productive", "slow_worker" },
    { "heavyweight", "featherweight" },
    { "heavyweight", "lunger" },
    { "featherweight", "lunger" },
    { "wildcard", "even_keel" },
    { "lucky_dice", "unlucky_dice" },
    { "evasive", "sturdy" },
    { "provider", "timberwright" },
    { "provider", "provisioner" },
    { "provider", "sawbones" },
    { "provider", "sparky" },
    { "blacksmith", "provider" },
    { "greasemonkey", "provider" },
    { "clothier", "provider" },
    { "heavy_footed", "lumbering" },
    { "daydreamer", "oblivious" },
    { "meek", "timid" },
    { "hewer", "timid" },
    { "cudgeller", "timid" },
    { "thumper", "timid" },
    { "slasher", "timid" },
    { "cutter", "timid" },
    { "sticker", "timid" },
    { "snapshooter", "timid" },
    { "rifleman", "timid" },
    { "spotter", "timid" },
    { "limbsplitter", "timid" },
    { "bonebreaker", "timid" },
    { "skullcracker", "timid" },
    { "cleaver", "timid" },
    { "redhand", "timid" },
    { "longreach", "timid" },
    { "gunslinger", "timid" },
    { "dead_eye", "timid" },
    { "longshot", "timid" },
    { "hewer", "meek" },
    { "cudgeller", "meek" },
    { "meek", "thumper" },
    { "meek", "slasher" },
    { "cutter", "meek" },
    { "meek", "sticker" },
    { "meek", "snapshooter" },
    { "meek", "rifleman" },
    { "meek", "spotter" },
    { "limbsplitter", "meek" },
    { "bonebreaker", "meek" },
    { "meek", "skullcracker" },
    { "cleaver", "meek" },
    { "meek", "redhand" },
    { "longreach", "meek" },
    { "gunslinger", "meek" },
    { "dead_eye", "meek" },
    { "longshot", "meek" },
    { "bonebreaker", "cleaver" },
    { "bonebreaker", "cudgeller" },
    { "bonebreaker", "dead_eye" },
    { "bonebreaker", "gunslinger" },
    { "bonebreaker", "limbsplitter" },
    { "bonebreaker", "longreach" },
    { "bonebreaker", "longshot" },
    { "bonebreaker", "redhand" },
    { "bonebreaker", "skullcracker" },
    { "cleaver", "dead_eye" },
    { "cleaver", "gunslinger" },
    { "cleaver", "limbsplitter" },
    { "cleaver", "longreach" },
    { "cleaver", "longshot" },
    { "cleaver", "redhand" },
    { "cleaver", "skullcracker" },
    { "cleaver", "slasher" },
    { "cutter", "redhand" },
    { "dead_eye", "gunslinger" },
    { "dead_eye", "limbsplitter" },
    { "dead_eye", "longreach" },
    { "dead_eye", "longshot" },
    { "dead_eye", "redhand" },
    { "dead_eye", "rifleman" },
    { "dead_eye", "skullcracker" },
    { "dead_eye", "snapshooter" },
    { "dead_eye", "spotter" },
    { "gunslinger", "limbsplitter" },
    { "gunslinger", "longreach" },
    { "gunslinger", "longshot" },
    { "gunslinger", "redhand" },
    { "gunslinger", "rifleman" },
    { "gunslinger", "skullcracker" },
    { "gunslinger", "snapshooter" },
    { "gunslinger", "spotter" },
    { "hewer", "limbsplitter" },
    { "limbsplitter", "longreach" },
    { "limbsplitter", "longshot" },
    { "limbsplitter", "redhand" },
    { "limbsplitter", "skullcracker" },
    { "longreach", "longshot" },
    { "longreach", "redhand" },
    { "longreach", "skullcracker" },
    { "longreach", "sticker" },
    { "longshot", "redhand" },
    { "longshot", "rifleman" },
    { "longshot", "skullcracker" },
    { "longshot", "snapshooter" },
    { "longshot", "spotter" },
    { "redhand", "skullcracker" },
    { "rifleman", "snapshooter" },
    { "rifleman", "spotter" },
    { "skullcracker", "thumper" },
    { "snapshooter", "spotter" },
    { "roofraiser", "timberwright" },
    { "cottager", "provisioner" },
    { "first_aid", "sawbones" },
    { "tinkerer_t", "sparky" },
    { "metalhand", "blacksmith" },
    { "oilhand", "greasemonkey" },
    { "patcher", "clothier" },
    { "forage_chemicals", "forage_bones" },
    { "forage_chemicals", "forage_alcohol" },
    { "forage_chemicals", "forage_ores" },
    { "forage_chemicals", "forage_urban" },
    { "forage_bones", "forage_alcohol" },
    { "forage_bones", "forage_ores" },
    { "forage_bones", "forage_urban" },
    { "forage_alcohol", "forage_ores" },
    { "forage_alcohol", "forage_urban" },
    { "forage_ores", "forage_urban" },
    { "addiction_alcohol", "addiction_opiate" },
    { "addiction_alcohol", "addiction_stimulant" },
    { "addiction_alcohol", "addiction_depressant" },
    { "addiction_alcohol", "addiction_hallucinogen" },
    { "addiction_alcohol", "addiction_inhalant" },
    { "addiction_opiate", "addiction_stimulant" },
    { "addiction_opiate", "addiction_depressant" },
    { "addiction_opiate", "addiction_hallucinogen" },
    { "addiction_opiate", "addiction_inhalant" },
    { "addiction_stimulant", "addiction_depressant" },
    { "addiction_stimulant", "addiction_hallucinogen" },
    { "addiction_stimulant", "addiction_inhalant" },
    { "addiction_depressant", "addiction_hallucinogen" },
    { "addiction_depressant", "addiction_inhalant" },
    { "addiction_hallucinogen", "addiction_inhalant" },
}

O.choiceGroups = {
    {
        key = "forage",
        title = "Choose an extra foraging group",
        text = "Your wilderness training lets your Foraging skill find one extra resource group.",
        parents = { "woodsman", "provider" },
        options = { "forage_chemicals", "forage_bones", "forage_alcohol", "forage_ores", "forage_urban" },
    },
    {
        key = "addiction",
        title = "Choose your addiction",
        text = "Addict: start with one addiction of choice.",
        parents = { "addict" },
        options = { "addiction_alcohol", "addiction_opiate", "addiction_stimulant", "addiction_depressant", "addiction_hallucinogen", "addiction_inhalant" },
    },
}
