
local distributionTable = {
	-- 1, 0.75, 0.5
	
		all = {
			bin = {
				rolls = 4,
				items = {
					"Base.BakingPan", 0.75,
					"Base.BakingTray", 0.75,
					"Base.BakingTray", 0.75,
					"Base.BreadKnife", 0.5,
					"Base.ButterKnife", 0.5,
					"Base.TinOpener", 0.75,
					"Base.Pot", 0.75,
					"Base.EmptyJar", 1,
					"Base.JarLid", 1,
					"Base.Kettle", 0.75,
					"Base.Mugl", 0.75,
					"Base.MugSpiffo", 0.75,
					"Base.MugWhite", 0.75,
					"Base.Pan", 0.75,
					"Base.GridlePan", 0.75,
					"Base.KitchenKnife", 0.5,
					"Base.KitchenTongs", 0.75,
					"Base.MuffinTray", 0.75,
					"Base.RoastingPan", 0.75,
					"Base.RollingPin", 0.75,
					"Base.Saucepan", 0.75,
					"Base.Spatula", 0.5,
					"Base.Spoon", 0.5,
					"Base.Teacup", 0.5,
					"Base.BallPeenHammer", 0.75,
					"Base.ClubHammer", 0.75,
					"Base.Hammer", 0.75,
					"Base.LugWrench", 0.75,
					"Base.Needle", 0.75,
					"Base.Paintbrush", 0.5,
					"Base.Screwdriver", 0.5,
					"Base.TirePump", 0.5,
					"Base.WoodenMallet", 0.5,
					"Base.HandFork", 0.75,
					"farming.HandShovel", 0.75,
					"Base.Bleach", 0.75,
					"Base.CleaningLiquid", 0.75,
					"Base.Soap", 0.75,
					"Base.Sponge", 0.75,
					"Base.DishCloth", 0.75,
					"Base.BathTowel", 0.75,
					"Base.Pen", 0.75,
					"Base.BluePen", 0.75,
					"Base.RedPen", 0.75,
					"Base.Pencil", 0.75,
					"Base.Eraser", 0.75,
					"Base.Scissors", 0.75,
					"Base.AlarmClock2", 0.75,
					"Base.Scotchtape", 0.75,
					"Base.DuctTape", 0.75,
					"Base.Glue", 0.75,
					"Base.Woodglue", 0.75,
					"Base.Aluminum", 0.75,
					"Base.Sheet", 0.75,
					"Base.Tarp", 0.75,
					"Base.Yarn", 0.75,
					"Base.Battery", 0.5,
					"Base.Amplifier", 0.5,
					"Radio.ElectricWire", 0.5,
					"Base.ElectronicsScrap", 0.5,
					"Base.RadioReceiver", 0.5,
					"Base.RadioTransmitter", 0.5,
					"Base.Receiver", 0.5,
					"Radio.ScannerModule", 0.5,
					"Base.CordlessPhone", 0.75,
					"Base.Earbuds", 0.75,
					"Base.Headphones", 0.75,
					"Base.HomeAlarm", 0.75,
					"Base.Speaker", 0.75,
					"Base.Timer", 0.75,
					"Base.Remote", 0.75,
					"Base.VideoGame", 0.75,
					"Base.Camera", 0.75,
					"Base.LightBulb", 0.75,
					"Base.LightBulbRed", 0.75,
					"Base.LightBulbGreen", 0.75,
					"Base.LightBulbBlue", 0.75,
					"Base.LightBulbYellow", 0.75,
					"Base.LightBulbCyan", 0.75,
					"Base.LightBulbMagenta", 0.75,
					"Base.LightBulbOrange", 0.75,
					"Base.LightBulbPurple", 0.75,
					"Base.LightBulbPink", 0.75,
					"Base.CompostBag", 0.75,
					"farming.GardeningSprayCigarettes", 0.75,
					"Base.Fertilizer", 0.5,
					"Base.BackgammonBoard", 0.75,
					"Base.Bell", 0.75,
					"Base.ChessBlack", 0.75,
					"Base.GamePieceBlack", 0.75,
					"Base.PlateBlue", 0.75,
					"Base.Bricktoys", 0.75,
					"Base.CatToy", 0.75,
					"Base.CheckerBoard", 0.75,
					"Base.Comb", 0.75,
					"Base.Cube", 0.75,
					"Base.Dice", 0.75,
					"Base.DogChew", 0.75,
					"Base.BeerCanEmpty", 0.75,
					"Base.PopEmpty", 0.75,
					"Base.KnittingNeedles", 0.75,
					"Base.PlateOrange", 0.75,
					"Base.Locket", 0.75,
					"Base.PaperNapkins", 0.75,
					"Base.CuttingBoardPlastic", 0.75,
					"Base.PlasticTray", 0.75,
					"Base.Plate", 0.75,
					"Base.CardDeck", 0.75,
					"Base.PokerChips", 0.75,
					"Base.Razor", 0.75,
					"Base.GamePieceRed", 0.75,
					"Base.Straw", 0.75,
					"Base.ChessWhite", 0.75,
					"Base.GamePieceWhite", 0.75,
					"Base.CuttingBoardWooden", 0.75,
					"Base.Yoyo", 0.75,
					"Base.Baseball", 0.75,
					"Base.Basketball", 0.75,
					"Base.Dart", 0.75,
					"Base.Football", 0.75,
					"Base.GolfBall", 0.75,
					"Base.Poolball", 0.75,
					"Base.SoccerBall", 0.75,
					"Base.TennisBall", 0.75,                
				},
			},
			
		},
}
	table.insert(Distributions, 1, distributionTable);
	
	--for mod compat:
	SuburbsDistributions = distributionTable;