DL = DL or {}
DL.Config = DL.Config or {}
local C = DL.Config

local CHEM_ZONES  = { TownZone = 20, TrailerPark = 20, Nav = 10, Farm = 10, FarmLand = 10, Vegitation = 3 }
local BONE_ZONES  = { DeepForest = 30, Forest = 30, Vegitation = 20, FarmLand = 15, Farm = 15, Nav = 5 }
local BOOZE_ZONES = { TrailerPark = 25, TownZone = 20, Farm = 15, FarmLand = 10, Nav = 10, Forest = 5, DeepForest = 5 }
local ORE_ZONES   = { Nav = 20, DeepForest = 15, Forest = 15, Vegitation = 15, FarmLand = 10, Farm = 10, TownZone = 8, TrailerPark = 8 }
local TECH_ZONES  = { TownZone = 30, TrailerPark = 25, Nav = 15, Farm = 5, FarmLand = 5 }

local function scaled(zones, factor)
    local out = {}
    for zone, weight in pairs(zones) do
        out[zone] = math.max(1, math.floor(weight * factor + 0.5))
    end
    return out
end

local function common(zones)    return scaled(zones, 1.5) end
local function uncommon(zones)  return scaled(zones, 0.6) end
local function rare(zones)      return scaled(zones, 0.25) end
local function legendary(zones) return scaled(zones, 0.05) end

C.forageLists = C.forageLists or {

    {
        name       = "Carrion Eye: Remains",
        enabled    = true,
        condition  = { trait = "carrion_eye" },
        categories = { "Junk" },
        zones      = { TownZone = 1, TrailerPark = 1, Nav = 1, Farm = 1, FarmLand = 1, Vegitation = 1, Forest = 1, DeepForest = 1 },
        items = {
            {
                type = "Base.Wallet", min = 1, max = 1, xp = 10,
                extras = {
                    rolls = { 1, 3 },
                    pool = {
                        { "DLM.CrowCoinGold", 10 },
                        { "DLM.CrowCoinSilver", 10 },
                        { "DLM.CrowCoinIron", 10 },
                        { "Base.Lighter", 3 },
                        { "Base.Matches", 3 },
                        { "Base.Cigarettes", 3 },
                        { "Base.Pills", 2 },
                        { "Base.PillsBeta", 1 },
                        { "Base.PillsAntiDep", 1 },
                        { "Base.Bandage", 2 },
                        { "Base.Bullets9mm", 2 },
                        { "Base.Bullets38", 1 },
                        { "Base.ShotgunShells", 1 },
                        { "aerx.T1Pistol1", 1 },
                        { "Base.Battery", 2 },
                        { "Base.HandTorch", 1 },
                        { "Base.Necklace_Gold", 1 },
                        { "Base.Necklace_Silver", 1 },
                        { "Base.Ring_Right_RingFinger_Gold", 1 },
                        { "Base.WristWatch_Left_ClassicBlack", 1 },
                        { "Base.Pen", 1 },
                        { "Base.Pencil", 1 },
                        { "Base.Notebook", 1 },
                        { "Base.Chocolate", 2 },
                        { "Base.Crisps", 2 },
                        { "Base.Gum", 1 },
                        { "Base.KitchenKnife", 1 },
                        { "Base.Screwdriver", 1 },
                        { "Radio.WalkieTalkie2", 1 },
                        { "Base.CreditCard", 3 },
                        { "Base.Comb", 2 },
                        { "Base.Lipstick", 1 },
                        { "Base.Toothbrush", 1 },
                        { "Base.Glasses_Normal", 1 },
                        { "Base.Glasses_Reading", 1 },
                        { "Base.Earring_LoopLrg_Gold", 1 },
                        { "Base.Bracelet_BangleRightGold", 1 },
                        { "Base.Ring_Left_RingFinger_Silver", 1 },
                        { "Base.WristWatch_Right_DigitalBlack", 1 },
                        { "Base.Locket", 1 },
                        { "Base.Necklace_Pearl", 1 },
                        { "Base.Perfume", 1 },
                        { "Base.Cologne", 1 },
                        { "Base.PillsVitamins", 1 },
                        { "Base.PillsSleepingTablets", 1 },
                        { "Base.Bullets45", 1 },
                        { "Base.Bullets44", 1 },
                        { "Base.Lollipop", 1 },
                        { "Base.MintCandy", 1 },
                        { "Base.CardDeck", 1 },
                        { "Base.Dice", 1 },
                        { "Base.Earbuds", 1 },
                        { "Base.Magazine", 1 },
                        { "Base.Scissors", 1 },
                        { "Base.Tissue", 2 },
                    },
                },
            },
        },
    },
    {
        name       = "Carrion Eye: Shallow Cache",
        enabled    = true,
        condition  = { trait = "carrion_eye" },
        categories = { "Junk" },
        zones      = { TownZone = 1, TrailerPark = 1, Nav = 1, Farm = 1, FarmLand = 1, Vegitation = 1, Forest = 1, DeepForest = 1 },
        items = {
            {
                type = "Base.GroceryBag1", min = 1, max = 1, xp = 10,
                contents = {
                    rolls = { 3, 5 },
                    pool = {
                        { "DLM.CrowCoinGold", 5 },
                        { "DLM.CrowCoinSilver", 5 },
                        { "DLM.CrowCoinIron", 5 },
                        { "Base.TinnedBeans", 3 },
                        { "Base.CannedCorn", 3 },
                        { "Base.CannedChili", 2 },
                        { "Base.CannedBolognese", 2 },
                        { "Base.CannedCarrots2", 2 },
                        { "Base.CannedPeas", 2 },
                        { "Base.TunaTin", 2 },
                        { "Base.Dogfood", 1 },
                        { "Base.WaterBottleFull", 3 },
                        { "Base.Bandage", 3 },
                        { "Base.AlcoholWipes", 1 },
                        { "Base.Disinfectant", 1 },
                        { "Base.Pills", 2 },
                        { "Base.Bullets9mm", 2 },
                        { "Base.ShotgunShells", 2 },
                        { "Base.Bullets38", 1 },
                        { "Base.Nails", 2 },
                        { "Base.Screws", 1 },
                        { "Base.DuctTape", 2 },
                        { "Base.Twine", 1 },
                        { "Base.Matches", 3 },
                        { "Base.Lighter", 1 },
                        { "Base.Battery", 2 },
                        { "Base.Candle", 2 },
                        { "Base.Cigarettes", 2 },
                        { "Base.Money", 2 },
                        { "Base.Screwdriver", 1 },
                        { "Base.Hammer", 1 },
                        { "Base.TinOpener", 1 },
                        { "Base.HuntingKnife", 1 },
                        { "Base.SewingKit", 1 },
                        { "Base.Map", 1 },
                        { "Base.CannedPotato2", 2 },
                        { "Base.CannedTomato2", 2 },
                        { "Base.CannedMushroomSoup", 2 },
                        { "Base.CannedFruitCocktail", 1 },
                        { "Base.CannedPeaches", 1 },
                        { "Base.CannedPineapple", 1 },
                        { "Base.Rice", 1 },
                        { "Base.Pasta", 1 },
                        { "Base.PeanutButter", 1 },
                        { "Base.Honey", 1 },
                        { "Base.Salt", 1 },
                        { "Base.Sugar", 1 },
                        { "Base.Coffee2", 1 },
                        { "Base.Teabag2", 1 },
                        { "Base.BeefJerky", 2 },
                        { "Base.Crackers", 2 },
                        { "Base.Cereal", 1 },
                        { "Base.SunflowerSeeds", 2 },
                        { "Base.PillsVitamins", 1 },
                        { "Base.CottonBalls", 1 },
                        { "Base.Bandaid", 2 },
                        { "Base.Thread", 1 },
                        { "Base.Needle", 1 },
                        { "Radio.RadioRed", 1 },
                        { "Base.Garbagebag", 1 },
                    },
                },
            },
        },
    },
    {
        name       = "Carrion Eye: Fallen Traveler",
        enabled    = true,
        condition  = { trait = "carrion_eye" },
        categories = { "Junk" },
        zones      = { TownZone = 1, TrailerPark = 1, Nav = 1, Farm = 1, FarmLand = 1, Vegitation = 1, Forest = 1, DeepForest = 1 },
        items = {
            {
                type = "Base.Bag_DuffelBag", min = 1, max = 1, xp = 15,
                contents = {
                    rolls = { 4, 7 },
                    pool = {
                        { "DLM.CrowCoinGold", 10 },
                        { "DLM.CrowCoinSilver", 10 },
                        { "DLM.CrowCoinIron", 10 },
                        { "Base.WaterBottleFull", 3 },
                        { "Base.TinnedBeans", 2 },
                        { "Base.TinnedSoup", 2 },
                        { "Base.GranolaBar", 2 },
                        { "Base.Crackers", 2 },
                        { "Base.Bandage", 3 },
                        { "Base.Pills", 2 },
                        { "Base.Antibiotics", 1 },
                        { "Base.SutureNeedle", 1 },
                        { "Base.Tshirt_DefaultTEXTURE_TINT", 2 },
                        { "Base.Socks_Ankle", 2 },
                        { "Base.Hat_Beany", 1 },
                        { "Base.Sheet", 1 },
                        { "Base.Matches", 2 },
                        { "Base.Lighter", 2 },
                        { "Base.Battery", 2 },
                        { "Base.HandTorch", 1 },
                        { "Radio.WalkieTalkie3", 1 },
                        { "Base.Map", 1 },
                        { "Base.Money", 2 },
                        { "Base.Cigarettes", 2 },
                        { "Base.WhiskeyFull", 1 },
                        { "Base.HuntingKnife", 1 },
                        { "Base.Machete", 1 },
                        { "Base.HandAxe", 1 },
                        { "Base.Bullets9mm", 2 },
                        { "Base.Bullets45", 1 },
                        { "Base.ShotgunShells", 2 },
                        { "Base.223Bullets", 1 },
                        { "Base.DuctTape", 2 },
                        { "Base.Rope", 1 },
                        { "Base.Tarp", 1 },
                        { "Base.Splint", 1 },
                        { "Base.AlcoholBandage", 1 },
                        { "Base.FirstAidKit", 1 },
                        { "Base.PillsSleepingTablets", 1 },
                        { "Base.BeefJerky", 2 },
                        { "Base.Cereal", 1 },
                        { "Base.WaterBottleEmpty", 2 },
                        { "Base.Pot", 1 },
                        { "Base.Gloves_LeatherGloves", 1 },
                        { "Base.Socks_Long", 2 },
                        { "Base.Trousers_Denim", 1 },
                        { "Base.Jacket_Padded", 1 },
                        { "Base.Shoes_TrainerTINT", 1 },
                        { "Base.Hat_BaseballCapBlue", 1 },
                        { "Base.Vest_DefaultTEXTURE_TINT", 1 },
                        { "camping.CampingTentKit", 1 },
                        { "camping.CampfireKit", 1 },
                        { "Base.FishingLine", 1 },
                        { "Base.FishingTackle", 1 },
                        { "Base.FishingRod", 1 },
                        { "Base.BaseballBat", 1 },
                        { "Base.Crowbar", 1 },
                    },
                },
            },
        },
    },

    {
        name       = "Chemicals: Household & Garden",
        enabled    = true,
        condition  = { trait = "forage_chemicals" },
        categories = { "Junk" },
        zones      = CHEM_ZONES,
        items = {
            { type = "Base.CleaningLiquid2",             min = 1, max = 1, xp = 8,  zones = common(CHEM_ZONES) },
            { type = "Base.Soap2",                       min = 1, max = 2, xp = 5,  zones = common(CHEM_ZONES) },
            { type = "Base.GluePaintBinder",             min = 1, max = 1, xp = 8,  zones = uncommon(CHEM_ZONES) },
            { type = "Base.Solvent",                     min = 1, max = 1, xp = 8,  zones = uncommon(CHEM_ZONES) },
            { type = "farming.GardeningSprayCigarettes", min = 1, max = 1, xp = 10, zones = { Farm = 15, FarmLand = 15, TownZone = 5, TrailerPark = 5 } },
            { type = "farming.GardeningSprayBonemeal",   min = 1, max = 1, xp = 10, zones = { Farm = 10, FarmLand = 10, TownZone = 3, TrailerPark = 3 } },
            { type = "Base.WaterBottlePetrol",           min = 1, max = 1, xp = 10, zones = uncommon(CHEM_ZONES) },
            { type = "Base.PetrolBleachBottle",          min = 1, max = 1, xp = 10, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.RexonaDesodorante",       min = 1, max = 1, xp = 5,  zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.OldSpiceDesodorante",     min = 1, max = 1, xp = 5,  zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.AxeDesodorante",          min = 1, max = 1, xp = 5,  zones = uncommon(CHEM_ZONES) },
        },
    },
    {
        name       = "Chemicals: Reagents & Powders",
        enabled    = true,
        condition  = { trait = "forage_chemicals" },
        categories = { "Junk" },
        zones      = CHEM_ZONES,
        items = {
            { type = "DrugsDLC.AmmoniaBottle",     min = 1, max = 1, xp = 12, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.EthanolBottle",     min = 1, max = 1, xp = 12, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.PotassiumBottle",   min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.IodoricAcidBottle", min = 1, max = 1, xp = 15, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.PhenyBottle",       min = 1, max = 1, xp = 15, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.Neoprene",          min = 1, max = 1, xp = 10, zones = uncommon(CHEM_ZONES) },
            { type = "aerx.BlackPowder",           min = 1, max = 1, xp = 15, zones = rare(CHEM_ZONES) },
            { type = "aerx.IGunpowder",            min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            {
                type = "B42Bags.Bag_ProtectiveCaseBulkyHazard", min = 1, max = 1, xp = 25, zones = legendary(CHEM_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "Base.Bleach", 3 },
                        { "Base.CleaningLiquid2", 3 },
                        { "Base.Disinfectant", 2 },
                        { "Base.AlcoholWipes", 2 },
                        { "DrugsDLC.AmmoniaBottle", 2 },
                        { "DrugsDLC.EthanolBottle", 2 },
                        { "DrugsDLC.PotassiumBottle", 2 },
                        { "DrugsDLC.IodoricAcidBottle", 1 },
                        { "DrugsDLC.PhenyBottle", 1 },
                        { "Base.GunPowder", 1 },
                        { "aerx.BlackPowder", 1 },
                        { "Base.Solvent", 2 },
                        { "Base.Glue", 2 },
                        { "Base.Woodglue", 1 },
                        { "Base.Fertilizer", 1 },
                        { "Base.Hat_NBCmask", 1 },
                        { "Base.Gloves_Surgical", 2 },
                        { "Base.Hat_SurgicalMask_Blue", 2 },
                    },
                },
            },
        },
    },

    {
        name       = "Chemicals: Pharmaceuticals & Precursors",
        enabled    = true,
        condition  = { trait = "forage_chemicals" },
        categories = { "Junk" },
        zones      = CHEM_ZONES,
        items = {
            { type = "DrugsDLC.TylenolBox", min = 1, max = 1, xp = 8, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.PanadolBox", min = 1, max = 1, xp = 8, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.IbuprofenBox", min = 1, max = 1, xp = 8, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.AcetaminophenBottle", min = 1, max = 1, xp = 8, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.EphedrineBottle", min = 1, max = 1, xp = 12, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.CodeineBottle", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.MorphineBottle", min = 1, max = 1, xp = 15, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.OxycodoneBottle", min = 1, max = 1, xp = 15, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.VicodinBottle", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.PercoBottle", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.XanaxBottle", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.AdderallBottle", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.ClonazepamBox", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.PhenobarbitalBox", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.TramadolBox", min = 1, max = 1, xp = 12, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.TentramitrozonBox", min = 1, max = 1, xp = 15, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.DrugPipe", min = 1, max = 1, xp = 5, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.Needle", min = 1, max = 2, xp = 5, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.BolsaDeDroga", min = 1, max = 3, xp = 3, zones = uncommon(CHEM_ZONES) },
            { type = "DrugsDLC.RawShrooms", min = 1, max = 3, xp = 12, zones = { DeepForest = 3, Forest = 3, Vegitation = 2, FarmLand = 1 } },
            { type = "DrugsDLC.Peyote", min = 1, max = 1, xp = 15, zones = { Vegitation = 1, FarmLand = 1, TrailerPark = 1 } },
            { type = "DrugsDLC.Ayahuasca", min = 1, max = 1, xp = 15, zones = { DeepForest = 1, Forest = 1, TownZone = 1 } },
            { type = "DrugsDLC.Escopolamina", min = 1, max = 1, xp = 15, zones = { Vegitation = 1, Forest = 1, TownZone = 1 } },
            {
                type = "B42Bags.Bag_ProtectiveCaseSmall", min = 1, max = 1, xp = 25, zones = legendary(CHEM_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "DrugsDLC.EphedrineCompound", 2 },
                        { "DrugsDLC.PhenyCompound", 2 },
                        { "DrugsDLC.MethCompound", 1 },
                        { "DrugsDLC.CocaCompound", 1 },
                        { "DrugsDLC.BenzoCompound", 1 },
                        { "DrugsDLC.EphedrineBottle", 2 },
                        { "DrugsDLC.PhenyBottle", 1 },
                        { "DrugsDLC.IodoricAcidBottle", 1 },
                        { "DrugsDLC.AmmoniaBottle", 2 },
                        { "DrugsDLC.EthanolBottle", 2 },
                        { "DrugsDLC.PotassiumBottle", 1 },
                        { "Base.MortarPestle", 1 },
                        { "Base.Spoon", 2 },
                        { "Base.Lighter", 2 },
                        { "Base.Gloves_Surgical", 2 },
                        { "Base.Hat_DustMask", 1 },
                        { "Base.Hat_GasMask", 1 },
                    },
                },
            },
        },
    },
    {
        name       = "Chemicals: Street Drugs",
        enabled    = true,
        condition  = { trait = "forage_chemicals" },
        categories = { "Junk" },
        zones      = CHEM_ZONES,
        items = {
            { type = "DrugsDLC.CodeineN", min = 1, max = 2, xp = 8, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.VicodinN", min = 1, max = 2, xp = 8, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.PercocetN", min = 1, max = 2, xp = 8, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.TramadolN", min = 1, max = 2, xp = 8, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.ClonazepamN", min = 1, max = 2, xp = 8, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.XanaxN", min = 1, max = 2, xp = 8, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.OxycodoneN", min = 1, max = 2, xp = 10, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.AmphetaminesN", min = 1, max = 1, xp = 10, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.MDMAN", min = 1, max = 2, xp = 10, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.ShroomsN", min = 1, max = 2, xp = 10, zones = rare(CHEM_ZONES) },
            { type = "DrugsDLC.AcidN", min = 1, max = 2, xp = 12, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.CocaineN", min = 1, max = 1, xp = 12, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.CrackN", min = 1, max = 1, xp = 12, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.MethN", min = 1, max = 1, xp = 12, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.HeroinN", min = 1, max = 1, xp = 12, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.DMTN", min = 1, max = 1, xp = 15, zones = legendary(CHEM_ZONES) },
            { type = "DrugsDLC.LeanN", min = 1, max = 1, xp = 8, zones = { TrailerPark = 1, TownZone = 1 } },
            { type = "DrugsDLC.FentanylN", min = 1, max = 1, xp = 20, zones = { TrailerPark = 1, TownZone = 1 } },
            {
                type = "B42Bags.CigarBox", min = 1, max = 1, xp = 25, zones = legendary(CHEM_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "DrugsDLC.BolsaDeDroga", 3 },
                        { "DrugsDLC.DrugPipe", 2 },
                        { "DrugsDLC.Needle", 2 },
                        { "Base.Money", 3 },
                        { "Base.Lighter", 2 },
                        { "DrugsDLC.XanaxN", 2 },
                        { "DrugsDLC.OxycodoneN", 2 },
                        { "DrugsDLC.MDMAN", 2 },
                        { "DrugsDLC.AmphetaminesN", 2 },
                        { "DrugsDLC.CocaineN", 1 },
                        { "DrugsDLC.MethN", 1 },
                        { "DrugsDLC.HeroinN", 1 },
                        { "DrugsDLC.BagShrooms", 1 },
                        { "DrugsDLC.AmphSales", 1 },
                        { "DrugsDLC.RefinedCoca", 1 },
                        { "DrugsDLC.RefinedHeroin", 1 },
                        { "DrugsDLC.Blockcocaine", 1 },
                    },
                },
            },
        },
    },

    {
        name       = "Bones & Hide: Remains",
        enabled    = true,
        condition  = { trait = "forage_bones" },
        categories = { "DeadAnimals" },
        zones      = BONE_ZONES,
        items = {
            { type = "aerx.SmallAnimalBone",        min = 1, max = 3, xp = 5,  zones = common(BONE_ZONES) },
            { type = "aerx.AnimalBone",             min = 1, max = 2, xp = 8,  zones = common(BONE_ZONES) },
            { type = "aerx.LargeAnimalBone",        min = 1, max = 1, xp = 10, zones = uncommon(BONE_ZONES) },
            { type = "aerx.HerbivoreTeeth",         min = 1, max = 3, xp = 5,  zones = uncommon(BONE_ZONES) },
            { type = "aerx.JawboneBovide",          min = 1, max = 1, xp = 10, zones = uncommon(BONE_ZONES) },
            { type = "aerx.PigTusk",                min = 1, max = 2, xp = 10, zones = rare(BONE_ZONES) },
            { type = "aerx.Rabbit_Skull",           min = 1, max = 1, xp = 8,  zones = uncommon(BONE_ZONES) },
            { type = "aerx.Raccoon_Skull",          min = 1, max = 1, xp = 8,  zones = uncommon(BONE_ZONES) },
            { type = "aerx.Turkey_Skull",           min = 1, max = 1, xp = 8,  zones = rare(BONE_ZONES) },
            { type = "aerx.Chicken_Hen_Skull",      min = 1, max = 1, xp = 8,  zones = { Farm = 8, FarmLand = 8, TrailerPark = 2 } },
            { type = "aerx.DeerDoe_Skull",          min = 1, max = 1, xp = 12, zones = rare(BONE_ZONES) },
            { type = "aerx.DeerStag_Skull",         min = 1, max = 1, xp = 15, zones = { DeepForest = 3, Forest = 2, Vegitation = 1 } },
            { type = "aerx.Sheep_Skull",            min = 1, max = 1, xp = 12, zones = { Farm = 4, FarmLand = 4 } },
            { type = "aerx.Pig_Skull",              min = 1, max = 1, xp = 12, zones = { Farm = 4, FarmLand = 4 } },
            { type = "aerx.Cow_Skull",              min = 1, max = 1, xp = 15, zones = { Farm = 3, FarmLand = 3 } },
            { type = "aerx.Bull_Skull",             min = 1, max = 1, xp = 20, zones = { Farm = 1, FarmLand = 1 } },
            { type = "aerx.Hominid_Skull_Fragment", min = 1, max = 1, xp = 25, zones = { DeepForest = 1, Forest = 1 } },
        },
    },
    {
        name       = "Bones & Hide: Pelts",
        enabled    = true,
        condition  = { trait = "forage_bones" },
        categories = { "DeadAnimals" },
        zones      = BONE_ZONES,
        items = {
            { type = "aerx.RabbitLeather_Full",           min = 1, max = 1, xp = 10, zones = uncommon(BONE_ZONES) },
            { type = "aerx.DeerLeather_Full",             min = 1, max = 1, xp = 15, zones = rare(BONE_ZONES) },
            { type = "aerx.SheepLeather_Full",            min = 1, max = 1, xp = 12, zones = { Farm = 5, FarmLand = 5, Vegitation = 1 } },
            { type = "aerx.PigLeather_Landrace_Full",     min = 1, max = 1, xp = 12, zones = { Farm = 4, FarmLand = 4 } },
            { type = "aerx.CowLeather_Holstein_Full",     min = 1, max = 1, xp = 15, zones = { Farm = 2, FarmLand = 2 } },
            { type = "aerx.RabbitLeather_Fur_Tan",        min = 1, max = 1, xp = 15, zones = legendary(BONE_ZONES) },
            { type = "aerx.LeatherStripsBundle",          min = 1, max = 1, xp = 10, zones = rare(BONE_ZONES) },
            {
                type = "B42Bags.Bag_HideSack", min = 1, max = 1, xp = 20, zones = legendary(BONE_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "aerx.SmallAnimalBone", 3 },
                        { "aerx.AnimalBone", 3 },
                        { "aerx.LargeAnimalBone", 1 },
                        { "aerx.HerbivoreTeeth", 2 },
                        { "aerx.PigTusk", 1 },
                        { "aerx.RabbitLeather_Full", 2 },
                        { "aerx.DeerLeather_Full", 1 },
                        { "aerx.DeerLeather_Fur_Tan", 1 },
                        { "Base.LeatherStrips", 2 },
                        { "Base.LeatherStripsDirty", 3 },
                        { "aerx.Needle_Bone", 1 },
                        { "Base.Twine", 2 },
                        { "Base.HuntingKnife", 1 },
                        { "Base.TrapSnare", 1 },
                    },
                },
            },
        },
    },

    {
        name       = "Alcohol: Bottles",
        enabled    = true,
        condition  = { trait = "forage_alcohol" },
        categories = { "Junk" },
        zones      = BOOZE_ZONES,
        items = {
            { type = "Deadline.BeerLager",       min = 1, max = 2, xp = 5,  zones = common(BOOZE_ZONES) },
            { type = "Deadline.BeerAle",         min = 1, max = 2, xp = 5,  zones = uncommon(BOOZE_ZONES) },
            { type = "Deadline.BeerStout",       min = 1, max = 1, xp = 5,  zones = uncommon(BOOZE_ZONES) },
            { type = "Deadline.BeerIPA",         min = 1, max = 1, xp = 5,  zones = uncommon(BOOZE_ZONES) },
            { type = "Deadline.CiderApple",      min = 1, max = 1, xp = 5,  zones = uncommon(BOOZE_ZONES) },
            { type = "Deadline.Kvass",           min = 1, max = 1, xp = 8,  zones = rare(BOOZE_ZONES) },
            { type = "Deadline.Mead",            min = 1, max = 1, xp = 8,  zones = rare(BOOZE_ZONES) },
            { type = "Deadline.WineGrape",       min = 1, max = 1, xp = 8,  zones = uncommon(BOOZE_ZONES) },
            { type = "Deadline.WineApple",       min = 1, max = 1, xp = 8,  zones = rare(BOOZE_ZONES) },
            { type = "Deadline.Vodka",           min = 1, max = 1, xp = 10, zones = uncommon(BOOZE_ZONES) },
            { type = "Deadline.Rakija",          min = 1, max = 1, xp = 10, zones = rare(BOOZE_ZONES) },
            { type = "Deadline.SchnappsPlum",    min = 1, max = 1, xp = 10, zones = rare(BOOZE_ZONES) },
            { type = "Deadline.SchnappsPeach",   min = 1, max = 1, xp = 10, zones = rare(BOOZE_ZONES) },
            { type = "Deadline.LiquerCoffee",    min = 1, max = 1, xp = 10, zones = rare(BOOZE_ZONES) },
            { type = "Deadline.LiquerCherry",    min = 1, max = 1, xp = 10, zones = rare(BOOZE_ZONES) },
            { type = "Deadline.Sake",            min = 1, max = 1, xp = 12, zones = legendary(BOOZE_ZONES) },
            {
                type = "B42Bags.CoolerB42", min = 1, max = 1, xp = 20, zones = legendary(BOOZE_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "Base.BeerCan", 4 },
                        { "Base.BeerBottle", 4 },
                        { "Deadline.BeerLager", 3 },
                        { "Deadline.BeerWheatBeer", 2 },
                        { "Deadline.BeerFruitCherry", 1 },
                        { "Deadline.CiderPear", 2 },
                        { "Base.Wine", 2 },
                        { "Base.Wine2", 2 },
                        { "Base.WhiskeyFull", 2 },
                        { "Deadline.Vodka", 2 },
                        { "Deadline.SchnappsApple", 1 },
                        { "Deadline.LiquerOrange", 1 },
                        { "Deadline.Mead", 1 },
                    },
                },
            },
        },
    },
    {
        name       = "Alcohol: Distilling Supplies",
        enabled    = true,
        condition  = { trait = "forage_alcohol" },
        categories = { "Junk" },
        zones      = BOOZE_ZONES,
        items = {
            { type = "Base.Yeast",                       min = 1, max = 2, xp = 8,  zones = uncommon(BOOZE_ZONES) },
            { type = "Base.Cork",                        min = 1, max = 4, xp = 3,  zones = common(BOOZE_ZONES) },
            { type = "aerx.BottleOpener",                min = 1, max = 1, xp = 5,  zones = uncommon(BOOZE_ZONES) },
            { type = "SP.SackProduce_Hops",              min = 1, max = 1, xp = 15, zones = { Farm = 3, FarmLand = 3, TrailerPark = 1 } },
            { type = "SP.SackProduce_SugarCane",         min = 1, max = 1, xp = 15, zones = { Farm = 2, FarmLand = 2 } },
            { type = "Deadline.MashAppleWine",           min = 1, max = 1, xp = 15, zones = { Farm = 2, FarmLand = 2, TrailerPark = 1 } },
            { type = "Base.BrewingStationConstructionSet", min = 1, max = 1, xp = 30, zones = { Farm = 1, FarmLand = 1, TrailerPark = 1, Forest = 1 } },
            { type = "Base.DistillerConstructionSet",    min = 1, max = 1, xp = 30, zones = { Farm = 1, FarmLand = 1, TrailerPark = 1, DeepForest = 1 } },
            {
                type = "B42Bags.Bag_Gunny", min = 1, max = 1, xp = 20, zones = rare(BOOZE_ZONES),
                contents = {
                    rolls = { 4, 7 },
                    pool = {
                        { "Base.Sugar", 3 },
                        { "Base.SugarBrown", 2 },
                        { "Base.Yeast", 3 },
                        { "Base.Cork", 3 },
                        { "Base.WineEmpty", 2 },
                        { "Base.WhiskeyEmpty", 2 },
                        { "Base.BeerEmpty", 2 },
                        { "Base.EmptyJar", 2 },
                        { "Base.JarLid", 2 },
                        { "aerx.CopperScrap", 2 },
                        { "aerx.CopperFragments", 2 },
                        { "Base.Twine", 1 },
                        { "Base.Corkscrew", 1 },
                        { "Deadline.Rakija", 1 },
                        { "Deadline.Vodka", 1 },
                    },
                },
            },
        },
    },

    {
        name       = "Ores: Veins & Scrap",
        enabled    = true,
        condition  = { trait = "forage_ores" },
        categories = { "Stones" },
        zones      = ORE_ZONES,
        items = {
            { type = "aerx.IronFragments",     min = 1, max = 3, xp = 5,  zones = common(ORE_ZONES) },
            { type = "aerx.CopperFragments",   min = 1, max = 3, xp = 5,  zones = common(ORE_ZONES) },
            { type = "aerx.TinFragments",      min = 1, max = 3, xp = 5,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.LeadFragments",     min = 1, max = 3, xp = 5,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.ZincFragments",     min = 1, max = 3, xp = 5,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.NickelFragments",   min = 1, max = 2, xp = 6,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.AluminumFragments", min = 1, max = 3, xp = 5,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.IronChunk",         min = 1, max = 2, xp = 8,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.CopperChunk",       min = 1, max = 2, xp = 8,  zones = uncommon(ORE_ZONES) },
            { type = "aerx.TinChunk",          min = 1, max = 1, xp = 8,  zones = rare(ORE_ZONES) },
            { type = "aerx.LeadChunk",         min = 1, max = 1, xp = 8,  zones = rare(ORE_ZONES) },
            { type = "aerx.ZincChunk",         min = 1, max = 1, xp = 8,  zones = rare(ORE_ZONES) },
            { type = "aerx.NickelChunk",       min = 1, max = 1, xp = 10, zones = rare(ORE_ZONES) },
            { type = "aerx.AluminumChunk",     min = 1, max = 1, xp = 8,  zones = rare(ORE_ZONES) },
            { type = "aerx.SilverScrap",       min = 1, max = 2, xp = 15, zones = legendary(ORE_ZONES) },
            { type = "aerx.GoldScrap",         min = 1, max = 1, xp = 20, zones = { DeepForest = 1, Forest = 1, Nav = 1 } },
            { type = "aerx.Coke",              min = 1, max = 2, xp = 8,  zones = uncommon(ORE_ZONES) },
            { type = "DL_MetalLine.Junk_Slag", min = 1, max = 2, xp = 3,  zones = uncommon(ORE_ZONES) },
            {
                type = "aerx.Specimen_Minerals", min = 1, max = 1, xp = 25, zones = { DeepForest = 1, Forest = 1, Nav = 1, TownZone = 1 },
                extras = {
                    rolls = { 2, 4 },
                    pool = {
                        { "aerx.IronChunk", 3 },
                        { "aerx.CopperChunk", 3 },
                        { "aerx.TinChunk", 2 },
                        { "aerx.NickelChunk", 2 },
                        { "aerx.SilverScrap", 1 },
                        { "aerx.GoldScrap", 1 },
                    },
                },
            },
        },
    },
    {
        name       = "Ores: Metal Supplies",
        enabled    = true,
        condition  = { trait = "forage_ores" },
        categories = { "Stones" },
        zones      = ORE_ZONES,
        items = {
            { type = "DL_MetalLine.Scrap_Carbon_S",   min = 1, max = 2, xp = 5,  zones = uncommon(ORE_ZONES) },
            { type = "DL_MetalLine.Scrap_Chromium_S", min = 1, max = 2, xp = 6,  zones = uncommon(ORE_ZONES) },
            { type = "DL_MetalLine.Scrap_Titanium_S", min = 1, max = 1, xp = 10, zones = rare(ORE_ZONES) },
            { type = "DL_MetalLine.Scrap_Iron_L",     min = 1, max = 1, xp = 10, zones = rare(ORE_ZONES) },
            { type = "DL_MetalLine.Scrap_Copper_L",   min = 1, max = 1, xp = 10, zones = rare(ORE_ZONES) },
            { type = "DL_MetalLine.Ingot_IronImpure", min = 1, max = 1, xp = 15, zones = legendary(ORE_ZONES) },
            { type = "DL_MetalLine.Ingot_CopperImpure", min = 1, max = 1, xp = 15, zones = legendary(ORE_ZONES) },
            { type = "Base.SmallSheetMetal",          min = 1, max = 1, xp = 8,  zones = rare(ORE_ZONES) },
            {
                type = "B42Bags.GemBag", min = 1, max = 1, xp = 25, zones = { DeepForest = 1, Forest = 1, Nav = 1, TownZone = 1, TrailerPark = 1 },
                contents = {
                    rolls = { 2, 5 },
                    pool = {
                        { "aerx.GoldScrap", 2 },
                        { "aerx.SilverScrap", 3 },
                        { "aerx.CopperChunk", 3 },
                        { "aerx.NickelChunk", 2 },
                        { "DL_MetalLine.Scrap_Gold_S", 1 },
                        { "DL_MetalLine.Scrap_Silver_S", 2 },
                        { "DL_MetalLine.Ingot_SilverImpure", 1 },
                        { "DL_MetalLine.Ingot_GoldImpure", 1 },
                    },
                },
            },
        },
    },

    {
        name       = "Urban Tech: Electronics",
        enabled    = true,
        condition  = { trait = "forage_urban" },
        categories = { "Junk" },
        zones      = TECH_ZONES,
        items = {
            { type = "Radio.ElectricWire",        min = 1, max = 2, xp = 5,  zones = common(TECH_ZONES) },
            { type = "Base.LightBulb",            min = 1, max = 2, xp = 5,  zones = common(TECH_ZONES) },
            { type = "Base.Earbuds",              min = 1, max = 1, xp = 5,  zones = uncommon(TECH_ZONES) },
            { type = "Base.Headphones",           min = 1, max = 1, xp = 5,  zones = uncommon(TECH_ZONES) },
            { type = "Base.Remote",               min = 1, max = 1, xp = 5,  zones = uncommon(TECH_ZONES) },
            { type = "Base.CordlessPhone",        min = 1, max = 1, xp = 8,  zones = uncommon(TECH_ZONES) },
            { type = "Radio.CDplayer",            min = 1, max = 1, xp = 8,  zones = uncommon(TECH_ZONES) },
            { type = "Base.Disc",                 min = 1, max = 2, xp = 3,  zones = uncommon(TECH_ZONES) },
            { type = "Base.Amplifier",            min = 1, max = 1, xp = 10, zones = rare(TECH_ZONES) },
            { type = "Base.Receiver",             min = 1, max = 1, xp = 10, zones = rare(TECH_ZONES) },
            { type = "Base.Speaker",              min = 1, max = 1, xp = 10, zones = rare(TECH_ZONES) },
            { type = "Base.Timer",                min = 1, max = 1, xp = 10, zones = rare(TECH_ZONES) },
            { type = "Base.MotionSensor",         min = 1, max = 1, xp = 12, zones = rare(TECH_ZONES) },
            { type = "Radio.RadioReceiver",       min = 1, max = 1, xp = 12, zones = rare(TECH_ZONES) },
            { type = "Radio.RadioTransmitter",    min = 1, max = 1, xp = 15, zones = legendary(TECH_ZONES) },
            { type = "Radio.ScannerModule",       min = 1, max = 1, xp = 15, zones = legendary(TECH_ZONES) },
            { type = "Radio.WalkieTalkie3",       min = 1, max = 1, xp = 12, zones = rare(TECH_ZONES) },
            { type = "Base.HomeAlarm",            min = 1, max = 1, xp = 12, zones = rare(TECH_ZONES) },
            { type = "Base.CarBatteryCharger",    min = 1, max = 1, xp = 15, zones = legendary(TECH_ZONES) },
            { type = "Base.PDA",                  min = 1, max = 1, xp = 20, zones = legendary(TECH_ZONES) },
            { type = "RemoteLightsController.RemoteLightsController", min = 1, max = 1, xp = 15, zones = legendary(TECH_ZONES) },
            { type = "Base.MachinedComponents",   min = 1, max = 1, xp = 20, zones = legendary(TECH_ZONES) },
            { type = "Base.PrecisionParts",       min = 1, max = 1, xp = 25, zones = { TownZone = 1, TrailerPark = 1 } },
            {
                type = "B42Bags.Parcel_Medium", min = 1, max = 1, xp = 20, zones = rare(TECH_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "Base.ElectronicsScrap", 4 },
                        { "Radio.ElectricWire", 3 },
                        { "Base.Battery", 3 },
                        { "Base.LightBulb", 2 },
                        { "Base.LightBulbRed", 1 },
                        { "Base.LightBulbBlue", 1 },
                        { "Base.LightBulbGreen", 1 },
                        { "Base.Amplifier", 1 },
                        { "Base.Receiver", 1 },
                        { "Base.Timer", 1 },
                        { "Base.MotionSensor", 1 },
                        { "Base.Earbuds", 1 },
                        { "Base.Disc", 2 },
                        { "Base.VideoGame", 1 },
                        { "Radio.WalkieTalkie2", 1 },
                        { "Base.Remote", 1 },
                    },
                },
            },
        },
    },
    {
        name       = "Urban Tech: Hardware",
        enabled    = true,
        condition  = { trait = "forage_urban" },
        categories = { "Junk" },
        zones      = TECH_ZONES,
        items = {
            { type = "Base.Wrench",           min = 1, max = 1, xp = 8,  zones = uncommon(TECH_ZONES) },
            { type = "Base.Doorknob",         min = 1, max = 1, xp = 5,  zones = uncommon(TECH_ZONES) },
            { type = "Base.Padlock",          min = 1, max = 1, xp = 8,  zones = rare(TECH_ZONES) },
            { type = "Base.CombinationPadlock", min = 1, max = 1, xp = 8, zones = rare(TECH_ZONES) },
            { type = "aerx.WireStack",        min = 1, max = 1, xp = 12, zones = rare(TECH_ZONES) },
            { type = "aerx.BarbedWireStack",  min = 1, max = 1, xp = 12, zones = legendary(TECH_ZONES) },
            {
                type = "B42Bags.ToolRoll_Leather", min = 1, max = 1, xp = 20, zones = rare(TECH_ZONES),
                contents = {
                    rolls = { 3, 6 },
                    pool = {
                        { "Base.Screwdriver", 3 },
                        { "Base.Wrench", 2 },
                        { "Base.Hammer", 2 },
                        { "Base.Saw", 1 },
                        { "Base.Tweezers", 2 },
                        { "Base.Screws", 3 },
                        { "Base.Nails", 3 },
                        { "Base.Wire", 2 },
                        { "Base.DuctTape", 2 },
                        { "Base.Scotchtape", 2 },
                        { "Base.Glue", 1 },
                        { "Base.WeldingRods", 1 },
                        { "Base.Torch", 1 },
                        { "Base.Paperclip", 2 },
                        { "Base.Hinge", 1 },
                    },
                },
            },
        },
    },
}

C.forageTraitBonuses = C.forageTraitBonuses or {
    tracker = {
        visionBonus     = 0,
        weatherEffect   = 0,
        darknessEffect  = 0,
        specialisations = { DeadAnimals = 100, Animals = 50 },
    },
}

if DL.log ~= nil then
    DL.log("forage config loaded (" .. tostring(#C.forageLists) .. " list(s) defined)")
end
